#! /usr/bin/env python3

import socket
import webbrowser
from http.server import * 
from threading import Thread
from socketserver import ThreadingMixIn


# There is an issue using the standard HTTP server, on investigation 
# the behaviour appears to be caused by Chrome pre-opening 
# sockets, where the HTTPServer would wait indefintely until the 
# request was sent.
# This was fixed in 3.7 through the introduction of ThreadingHTTPServer
# Since we use 3.6 the below addresses that fix.


class Handler(SimpleHTTPRequestHandler):
    pass


class ThreadingHTTPServer(ThreadingMixIn, HTTPServer):
    pass


def serve_at(ip, port):
    server = ThreadingHTTPServer((ip, port), Handler)
    server.serve_forever()


PORT = 8000
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
ip = s.getsockname()[0]
s.close()

ip_addr = f"http://{ip}:{PORT}"
print(f"Serving at: {ip_addr}")

Thread(target=serve_at, args=[ip, PORT]).start()
webbrowser.open(ip_addr)

