#! /usr/bin/env python3

import socket
import webbrowser
from http.server import * 


PORT = 8000


def run_server(server_class=HTTPServer, handler_class=SimpleHTTPRequestHandler):
    server_address = ('', PORT)
    httpd = server_class(server_address, handler_class)
    httpd.serve_forever()


s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
ip = s.getsockname()[0]
s.close()


print(f"Serving on ip {ip}:{PORT}")
webbrowser.open(f"http://{ip}:{PORT}")
run_server()


